version: '3.8'
services:
  puppeteer-test:
    build: .
    container_name: puppeteer-test
    env_file: .env  # Указываем файл с переменными окружения
    volumes:
      - ./puppeteer-screenshots:/app/screenshots  # Монтируем локальную директорию